### PR TITLE
Feature update v2ray vless xtls supports for clients

### PR DESCRIPTION
**Pull request by darwinchow**

### CODE REVIEW

**Comment by MrVb0** [comment]
Hello, thanks for your efforts, is this PR working correctly?

**Comment by darwinchow** [comment]
> Hello, thanks for your efforts, is this PR working correctly?

No. This PR has been closed permanently because VLESS and XTLS are not mainstream now. For VLESS, some clients do not support VLESS currently, and these unsupported clients will not be able to connect to servers if you use VLESS. For XTLS, see https://github.com/XTLS/Go/issues/16

**Comment by MrVb0** [comment]
thank you dear friend

In my opinion, the fact that vless or xtls is not supported in some clients should not prevent the development of the powerful v2board script.
Currently, many of the most famous clients in Android and Windows operating systems support vless and xtls (and even xtls-rprx-vision, which is the newest and best protocol).
Also, there are good clients in ios and mac that support vless+xtls.

In this way, the site manager can decide which protocol to use according to the needs of his customers and the conditions of his country.
For example, my clients only use fair vpn (ios), V2rayng (android) and v2rayn (windows)!

In some countries, vmess is quickly recognized by gfw! Also, unfortunately, trojan in v2board does not support websocket, so there is no proper way to connect with websocket and cdn...

Please, if you can help in adding vless + xtls / vless + xtls-rprx-vision / trojan+ws, do this favor.

Many v2board users are waiting for this feature and will appreciate your efforts.

Requests to add new protocols:
https://github.com/v2board/v2board/issues/666
https://github.com/v2board/v2board/issues/597
https://github.com/v2board/v2board/issues/394
https://github.com/v2board/v2board/issues/577
https://github.com/v2board/v2board/issues/607

vmess problems in some clients that have not been solved with any suggestions and guidance:
https://github.com/XrayR-project/XrayR/issues/240
https://github.com/XrayR-project/XrayR/issues/96
https://github.com/XTLS/Xray-core/issues/1285

**Comment by darwinchow** [comment]
Well... I'm so sorry for that. May I know which country your users mainly come from?

**Comment by MrVb0** [comment]
> Well... I'm so sorry about that. May I know which country your users mainly come from?

iran

**Comment by darwinchow** [comment]
> > Well... I'm so sorry about that. May I know which country your users mainly come from?
> 
> iran

Okay. For more details on enabling VLESS/XTLS on V2board, you can contact me via email on my profile.

**Comment by alijoon3376** [comment]
hi , Are these features working properly now?

**Pull request closed without merging**
